#pragma once

#ifndef CODE_HPP
#define CODE_HPP

enum {
	TOKEN_START = 0, TOKEN_END, TOKEN_IDENTIFIER, TOKEN_LOOKUP,
	TOKEN_COMMA, TOKEN_NUMBER, TOKEN_STRING, TOKEN_VECTOR,
	TOKEN_LPAREN, TOKEN_RPAREN, TOKEN_LBRAK, TOKEN_RBRAK,
	TOKEN_BODY, TOKEN_LBODY, TOKEN_BLOCK, TOKEN_INTERNLOOKUP,
	TOKEN_RBODY, TOKEN_UNKNOWN, TOKEN_EOL, TOKEN_COMMENT, TOKEN_FUNCTION,
	TOKEN_SEMICOLON, TOKEN_LIST, TOKEN_FUNCTIONCALL, MATH_PLUS, MATH_MINUS,
	ID_NUMBER, ID_STRING, ID_VECTOR, ID_FUNCTION, ID_BUILTIN, ID_MACRO,
	BLOCK_IF, BLOCK_ELSE, BLOCK_LOOP, BLOCK_DO, BLOCK_WHILE, 
	BLOCK_CASE, BLOCK_SWITCH, BLOCK_DEFAULT, BLOCK_ENUM,
	OVERRIDE_ABORT, OVERRIDE_EXIT
};

#endif